version: 2.1

orbs: 
  node: circleci/node@2.1.1
  codecov: codecov/codecov@1.0.2

jobs:
  test:
    steps:
      - checkout
      - restore_cache:
          name: Restore Workspace Cache
          keys:
            - yarn-workspace-{{ checksum "yarn.lock" }}
      - run: 
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: yarn-workspace-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - example/node_modules
            - network/node_modules
            - react-native/node_modules
      - run: yarn workspace @app-up/network test --coverage
      - run: yarn workspace @app-up/react-native test --coverage
      - codecov/upload:
          file: packages/network/coverage
          upload_name: network
      - codecov/upload:
          file: packages/react-native/coverage
          upload_name: react-native

workflows:
  version: 2.1
  jobs:
    - test