jobs:
  install-project:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          name: Restore Workspace Cache
          keys:
            - yarn-workspace-{{ checksum "yarn.lock" }}
      - run: 
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: yarn-workspace-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - example/node_modules
            - network/node_modules
            - react-native/node_modules
  test:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          name: Restore Workspace Cache
          keys:
            - yarn-workspace-{{ checksum "yarn.lock" }}
      - run: 
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: yarn-workspace-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - example/node_modules
            - network/node_modules
            - react-native/node_modules
      - run: yarn workspace @app-up/network test --coverage
      - run: yarn workspace @app-up/react-native test --coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-project
      - test